_BASE_: "../Base-RCNN.yaml"
MODEL:
  # WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  WEIGHTS: "pretrained_weights/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 5
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_novelx_1shot_seedx", )
  # TEST: ('voc_2007_test_novelx',)
  TEST: ()
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (640, )
  MAX_ITER: 800
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "pretrained_weights/R-101.pkl"
# VAE:
#   ENABLE: True
#   PATH: "checkpoints/defrcn_vae_model.pth" 
#   CLIP_PATH: "data/roifeats_base/clip_prototypes.npy"
OUTPUT_DIR: "checkpoints/voc/defrcnn/defrcnn_novelx_1shot_seedx"